import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Script from 'next/script'
import { useState } from 'react'

import { Dna } from 'react-loader-spinner'
import { useOnchain } from '../hooks/useOnchain'

import { wrapRelayx } from 'stag-relayx'

export default function Home() {

  //@ts-ignore
  const stag = wrapRelayx(relayone)

  const currentUser = false

  const posts = [{
    title: '	Activision’s faulty anti-cheat software',
    url: 'https://blog.mikeswanson.com/post/702753924034297856/activisions-faulty-anti-cheat-software',
    difficulty: 0,
    timestamp: 'timestamp',
    comments_count: 0,
    host: 'mikeswanson.com'
  }, {
    title: '	Activision’s faulty anti-cheat software',
    url: 'https://blog.mikeswanson.com/post/702753924034297856/activisions-faulty-anti-cheat-software',
    difficulty: 0,
    timestamp: 'timestamp',
    comments_count: 0,
    host: 'mikeswanson.com'
  }, {
    title: '	Activision’s faulty anti-cheat software',
    url: 'https://blog.mikeswanson.com/post/702753924034297856/activisions-faulty-anti-cheat-software',
    difficulty: 0,
    timestamp: 'timestamp',
    comments_count: 0,
    host: 'mikeswanson.com'
  }, {
    title: '	Activision’s faulty anti-cheat software',
    url: 'https://blog.mikeswanson.com/post/702753924034297856/activisions-faulty-anti-cheat-software',
    difficulty: 0,
    timestamp: 'timestamp',
    comments_count: 0,
    host: 'mikeswanson.com'
  }]

  console.log('posts', posts)

  const { data: rankings, error: rankingsError, loading: loading } = useOnchain('/rankings', '?app=alpha.news.pow.co')
  const { data: events, error: eventsError, loading: eventsLoading } = useOnchain('/events', '?app=alpha.news.pow.co')

  return (
    <div>
      <Head>
        <title>Boost News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

      </Head>

      <Script src="https://one.relayx.io/relayone.js" />

      <div className="container">



        <div className="header-container">

          <div className="header-logo">
            <Image alt='website icon' src="/images/y18.gif" width="18" height="18" />
          </div>

          <div className="header-menu-container">
            <div className="header-menu-links-left">
              <b className="header-menu-logo"><a href="/">Pow News</a></b>
              <div>
                <a href="#">top boosted</a> | 
                <a href="#">newest</a> | 
                <a href="#">comments</a> | 
                <a href="#">jobs</a> | 
                <Link href="/submit">submit</Link> | 
              </div>
            </div>
            <div className="header-menu-login-container">
              <span className="pagetop">
              {currentUser ? (
                <a href="#">Logout</a>
              ) : (
                <a href="#">Login</a>

              )}
              </span>
            </div>
          </div>
          
        </div>


      <div className="feed-container">

        {loading && (
          <div style={{textAlign: 'center'}}>
            <Dna
              visible={true}
              height="80"
              width="80"
              ariaLabel="dna-loading"
              wrapperStyle={{}}
              wrapperClass="dna-wrapper"
            />
          </div>
        )}

          {posts.map((post, index) => (

            <div className="post-container">
              <div className="post-header">
                <div className="post-number">{ index+1 }.</div>
                <div className="post-upvote-container">
                  <a href="#"><div className="post-upvote-arrow"></div></a>
                </div>
                <div>
                  <a href="{post.url}" className="post-link">{post.title}</a>
                  <span className="post-website">
                    &nbsp (<a href="#"><span>{post.host}</span></a>)
                  </span>
                </div>
              </div>
              <div className="post-footer">
                <span>{post.difficulty} ⛏️ </span>
                <span><>{post.timestamp} ago</></span>
                <span>| <a href="#">hide</a> </span>
                <span>
                  | 
                  <a href="#">comments</a>
                </span>
              </div>
            </div>
        ))}

        <div className="feed-footer-line"></div>
      </div>

    </div>
    </div>


  )
}
